title: Identity in Depth
description: IAM, Zero Trust, and Microsoft Security for regulated industries
author: John Nassar
url: "https://nassar-m.github.io"
theme: jekyll-theme-midnight
show_excerpts: true
plugins:
  - jekyll-feed
header_pages:
  - pages/identity-access.md
  - pages/zero-trust.md
  - pages/exchange.md
  - pages/automation.md
  - pages/compliance.md
  - about.md
